### ISSUE TITLE
I.CardIO.ipynb Error in line [6]

### ISSUE THREAD

**Issue by iv-med** [analysiscenter/cardio#20]
batch_with_data = batch_with_data.load(src='../cardio/tests/data/REFERENCE.csv', fmt='csv', components='target')
have to replace to 
batch_with_data = batch.load(src='../cardio/tests/data/REFERENCE.csv', fmt='csv', components='target')

**Comment by dpodvyaznikov** [comment]
Hi! Please, provide more information about the error you had, e.g. traceback output.
The correction you've suggested is wrong, because later in the tutorial you need signal to be loaded into `batch_with_data`. Originally, after you've loaded the signal and metadata with first `load` action in line chunk `[5]`, you load targets into the same batch. Thus that after execution of chunk `[6]` `batch_with_data` contains signal, metadata and targets.
If you apply `load` to `batch`, as in your suggestion, you would get new `batch_with_data` which only contains target, and code in the next chunks would not work.

**Comment by dpodvyaznikov** [comment]
I’m closing this issue because it has been inactive for a few weeks. This probably means that it is not reproducible or it has been fixed in a newer version. Please reopen if you still encounter this issue.
