### ISSUE TITLE
Training time with training2017 dataset

### ISSUE THREAD

**Issue by AnoopRKulkarni** [analysiscenter/cardio#34]
I ran the training session on NVIDIA Tegra Jetson TX2 GPU. The training2017 dataset contains ~8500 samples. Just how much training time this is supposed to take?

On above GPU, I needed 18 hours of training time. Is this normal (Ubuntu 16.04 LTS, TF 1.9 with GPU support) ?

~anoop

**Comment by DrAnoopKulkarni** [comment]
No - actually it didnt stop after 18 hours - ther was error so it exited ! 

From another thread, I read addiing following line helps.

.call(lambda _, v: print(v[-1]), v=V('loss_history'))

which prints loss function value at each iteration. That said, should it not exit at N_EPOCH=1000? Once I put this print, I can see that it goes on executing in infinite loop - where the iteration number exceeds tens of thousands in 18 hours..

On Jetson TX2, if my understanding is correct with above print appreaching at each iteration, 1000 iterations take about 2.5 hours - but the problem is it is not terminating at all !

Any leads please !

thanks and regards
~anoop

**Comment by AnoopRKulkarni** [comment]
Apologies. this was sorted out after spending some time with the code.
